version: '3.1'
services: 
  app:
    build:
      context: ./docker
      dockerfile: app.dockerfile
    volumes:
      - ./www:/var/www/
  web:
    build:
      context: ./docker
      dockerfile: web.dockerfile
    ports:
      - 80:80
    volumes_from:
      - app